# -*- coding: utf-8 -*-
"""FloydWarshallAlg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tqoHcs3vg4G5BGDuNNzXeNoiERBqlJAL
"""

def floyd_warshall(graph):
    n = len(graph)
    dist = [row[:] for row in graph]

    for k in range(n):
        for i in range(n):
            for j in range(n):
                dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])

    return dist

graph = [
    [0, 3, 0, 7],
    [8, 0, 2, 0],
    [5, 0, 0, 1],
    [2, 0, 0, 0]
]

shortest_distances = floyd_warshall(graph)

for row in shortest_distances:
    print(row)